apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ng20ctv3x-nodejs 
  janus-idp.io/tekton: ng20ctv3x-nodejs
  backstage.io/kubernetes-id: ng20ctv3x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ng20ctv3x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml